language: python

cache: pip

python:
  - "3.6"
  - "3.7"

before_install:
  - export BOTO_CONFIG=/dev/null # https://github.com/spulec/moto/issues/1941

install:
  - pip install -U -r requirements.txt

script:
  - scripts/test

after_script:
  - codecov